name: Build AVClient

# Trigger the workflow on push to main branch or on pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner
    
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up MSBuild and .NET Framework (no need to use actions/setup-dotnet for .NET Framework)
      - name: Install .NET Framework
        run: |
          choco install visualstudio2019-workload-net-web --params "--quiet --includeOptional"

      # Step 3: Restore the dependencies using MSBuild (for .NET Framework)
      - name: Restore dependencies
        run: |
          msbuild /t:Restore AVClient.sln

      # Step 4: Build the WinForms application using MSBuild
      - name: Build AVClient
        run: |
          msbuild /p:Configuration=Release AVClient.sln

      # Optional: Publish the application (if you want to create an executable)
      - name: Publish WinForms application
        run: |
          msbuild /p:Configuration=Release /p:Platform="x86" /t:Publish AVClient.sln
